// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateAuthor(ctx context.Context, arg CreateAuthorParams) (User, error)
	DeleteAuthor(ctx context.Context, id int32) error
	GetAuthor(ctx context.Context, id int32) (User, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateAuthor(ctx context.Context, arg UpdateAuthorParams) error
}

var _ Querier = (*Queries)(nil)
